spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kata
    username: root
    password: password
  jpa:
    show-sql: off
    hibernate:
      ddl-auto: create
    open-in-view: off

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    operations-sorter: method