apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-application
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-application
    spec:
      containers:
        - name: spring-application-pod
          image: spring-application:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: spring-application