apiVersion: v1
kind: Service
metadata:
  name: spring-application-service
spec:
  selector:
    app: spring-application
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort